"""Add Prop Firm logic fields

Revision ID: bf983a974a14
Revises: c5667643644d
Create Date: 2026-01-18 01:47:17.146635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf983a974a14'
down_revision = 'c5667643644d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_start_equity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_daily_reset', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_column('last_daily_reset')
        batch_op.drop_column('daily_start_equity')

    # ### end Alembic commands ###
